### ISSUE TITLE
Axis2/c 1.7.0

### ISSUE THREAD

**Issue by alexis-gruet-deel** [loentar/axis2c-unofficial#15]
Hi @loentar 

.. and thanks for your great job. Is this project is always maintained ? Do you planed to merge w/ the current 1.7.0 ? I have some doubt regarding which version to use, yours or trunk 1.7.0

I saw several differences regarding om handling in axiom in 1.7.0 trunk

**Comment by loentar** [comment]
Hi,

This project is not actively maintained. But if you submit pull request or suggestion for code change, I will be happy to apply it.

If you are not sure which version to use, choose 1.6.0-unofficial with single-thread-mode, because it's well tested (but still have few bugs). I do not recommend to use 1.7.0, because it's very unstable. Not sure if it will be released some day. I do not plan to merge with 1.7.0 because all the patches very specific to 1.6.0.
